### ISSUE TITLE
Design the main layout

### ISSUE THREAD

**Issue by Smebbs** [IT2810/it2810-webutvikling-h18-prosjekt-3-14#1]
Includes mockups

**Comment by didriksg** [comment]
Registration screen
![image](https://user-images.githubusercontent.com/17567687/46102522-cc4fb680-c1ce-11e8-8d8f-520ac6ffa1e4.png)

Today screen
![image](https://user-images.githubusercontent.com/17567687/46102557-e8ebee80-c1ce-11e8-9607-0be50c495d4b.png)

**Comment by Gudzy** [comment]
Think this is enough for a starter. Navigation between the different screens is finished, including navigation between registration screen and the tab menu inside the application. Putting this up for review.

**Comment by Smebbs** [comment]
Seems good! :+1:

**Comment by Gudzy** [comment]
Great! Closing this issue and merging into 'develop'.
