### ISSUE TITLE
Implement profile editing

### ISSUE THREAD

**Issue by Gudzy** [IT2810/it2810-webutvikling-h18-prosjekt-3-14#11]
Using the same design as in registerscreen, except that it will be used for **editing** user data instead of **entering**.

**Comment by Gudzy** [comment]
Have implemented profile editing. All the setup with AsyncStorage is done. User data is now accesible all over the app. Putting this issue up for review.

**Comment by Smebbs** [comment]
This is good, reviewed

**Comment by Gudzy** [comment]
Glad to hear that. Closing this issue.
