### ISSUE TITLE
Design today tab

### ISSUE THREAD

**Issue by Smebbs** [IT2810/it2810-webutvikling-h18-prosjekt-3-14#4]

**Comment by didriksg** [comment]
Today tab is designed and functional. Setting this to review

**Comment by didriksg** [comment]
Noticed that there still are some features missing. Removing issue from review and continue development

**Comment by didriksg** [comment]
Added the missing features. The issue is ready for review

**Comment by Smebbs** [comment]
Reviewed, go ahead and merge.
