### ISSUE TITLE
Design settings/register tab

### ISSUE THREAD

**Issue by Smebbs** [IT2810/it2810-webutvikling-h18-prosjekt-3-14#5]

**Comment by Gudzy** [comment]
Done a lot of work on the registration page.  Think I can go on and make a similar page, just for **editing** the user information. Have a look at it and let me know what yout think. Putting this up for **Review.**

**Comment by Smebbs** [comment]
This is good, the test code used here can be used to close issue #9 so that we can start implementing the functionality for every tab when the design is complete. Reviewed.

**Comment by Gudzy** [comment]
Closing this issue. Continued the work with implementing editing user data in issue #11.
