### ISSUE TITLE
Implement visualization for "profile tab"

### ISSUE THREAD

**Issue by Smebbs** [IT2810/it2810-webutvikling-h18-prosjekt-3-14#8]

**Comment by Smebbs** [comment]
Blocked by #9

**Comment by Gudzy** [comment]
This is done. Putting it for review.

**Comment by Smebbs** [comment]
Did not work on android, however I fixed it, and it seems to work now. Ready to merge.

**Comment by Gudzy** [comment]
Fantastic! Closing this issue now and merging into develop.
